25-11-16/users/config/routes.rb
Rails.application.routes.draw do
  devise_for :users


	get 'users/sign_in'
	get 'users/sign_up'
	get 'users/sign_out' => 'users/index'
	get 'users/auth'
	get 'users/profile'
	get 'contacts/destroy'
	resources :users 
	    
	resources :profiles

	resources :contacts
	resources :addresses
    root to: "users#auth"
	
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

25-11-16/users/app/models/address.rb
class Address < ApplicationRecord
end

25-11-16/users/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

25-11-16/users/app/models/contact.rb
class Contact < ApplicationRecord
end

25-11-16/users/app/models/profile.rb
class Profile < ApplicationRecord
	
end

25-11-16/users/app/models/user.rb
# class EmailValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#       record.errors[attribute] << (options[:message] || "is not an email")
#     end
#   end
# end
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile, foreign_key: :user_id
	has_many :contacts, :foreign_key => "user_id"
    has_one :address, foreign_key: :user_id
	# validates :first_name, presence:true
	# validates :last_name, presence:true
	# validates :email, presence: true, email: true
	# validates :username,  presence:true,uniqueness: true
	# validates :password,  presence:true
	# validates :password_confirmation, presence:true
	# validates :password, confirmation:{ case_sensitive: false }
	# validates :mobile, length: {is: 10}, numericality: true
	# validates :fax, numericality: true
	# validate :country_cant_be_blank
	# def country_cant_be_blank
	# 	if country.blank?
	# 		errors.add(:country, "select country")
	# 	end
	# end


	accepts_nested_attributes_for :profile, :address
end

25-11-16/users/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

25-11-16/users/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?
	
	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u|
		u.permit(:first_name, :last_name, :middle_name, :gender, :email, :other_email, :address1, :address2, :city, :state, :country, :zip, :phone_no, :cell_no, :fax, :rank_id, :preferred_language, :username, :password, :password_confirmation, :paid_rank_id, :profile_id, :profile_attributes => [:first_name, :last_name, :email, :phone_no, :cell_no, :gender, :education, :address, :fax, :rank_id, :hometown, :story, :movies, :other_emails, :phone_visibility, :address_visibility, :email_visibility, :user_id],:address_attributes => [:address1, :address2, :city, :state, :country, :zip, :fax,:user_id])}  
	end
	def after_sign_out_path_for(resource_or_scope)
	    users_path
	end
 
end

25-11-16/users/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = current_user.contacts
		if @contacts.present?
			render "index"
		else
			flash[:notice] = "Contacts not exists"
			render "nocontact"
		end
	end

	def new
		@contact = Contact.new()
	end

	def edit
       @contact = Contact.find(params[:id])
    end

	def create		
		@contact = Contact.new(contact_params)
		@contact.user_id = current_user.id
		if @contact.save            
           render "show"
        else
       	  render 'new'
       	end		
	end
	
    def show
    	@contact = Contact.find(params[:id])
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy 
        redirect_to contacts_path
    end

    def nocontact
    end

	private
	
	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :contact_type, :address1, :address2, :city, :phone_number, :state, :birthday, :user_id)
	end
end

25-11-16/users/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

25-11-16/users/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index		
		@users = User.all	    
	end	

	def new
		@user = User.new
		@user.build_profile
		@user.contacts.build		
	end
        
    def auth
    	@profile = Profile.find_by user_id: current_user.id
    	render 'show'
    end	
    
	def create
		@user = User.new(user_params)
		if @user.save 
			@profile= Profile.where(user_id: @user.id).first
    		render 'profile'
        else
       	  render 'new'
       	end		
	end	

	def show
		@us = User.find_by(username: user_params[:username] ,password: user_params[:password])
	end

	private
    def user_params
       params.require(:user).permit(:first_name, :middle_name, :last_name, :gender, :preferred_language, :email, :other_email, :phone, :mobile, :address1, :address2, :fax, :rank_id, :city, :state, :country, :zip, :username, :password, :password_confirmation, :paid_rank_id, :profile_id, :profile_attributes => [:first_name, :phone, :email, :last_name, :fax, :cell, :address, :rank_id, :gender, :education, :hometown, :story, :movies, :phone_visibility, :email_visibility, :address_visibility, :other_emails, :user_id])
       
    end
    
end

25-11-16/users/app/helpers/addresses_helper.rb
module AddressesHelper
end

25-11-16/users/app/views/contacts/edit.html.erb
<h2 align= center ><strong>Editing Contact</strong></h2>
<%= simple_form_for @contact, method: :patch do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :contact_type %>
  <%= f.input :address1 %>
  <%= f.input :address2 %>
  <%= f.input :city %>
  <%= f.input :phone_number %>
  <%= f.input :state %>  
  <%= f.input :birthday %>
  <%= f.button :submit %>
 <% end %>
 <%= link_to 'Back', contact_path %>

25-11-16/users/app/views/contacts/index.html.erb
<h1>List of contacts</h1> 
<table>
  <tr>
    <th>First_Name</th>
    <th>Contact_Type</th>
    <th>Address</th>
    <th>City</th>
    <th>phone_number</th>
    <th>State</th>
    <th>Birthday</th>
  </tr> 
  <% @contacts.each do |f| %>
    <tr>
      <td><%= f.first_name%></td>
      <td><%= f.contact_type %></td>
      <td><%= f.address1 %></td>
      <td><%= f.city %></td>
      <td><%= f.phone_number %></td>
      <td><%= f.state %></td>
      <td><%= f.birthday %></td>
      <td><%= link_to 'show', f %></td>
      <td><%= link_to 'edit', edit_contact_path(f) %></td>
      <td><%= link_to 'destroy', f, method: :delete,data: {confirm: 'Are you sure'} %></td>
    </tr>
  <% end %>
  <%= link_to 'back', users_auth_path %>
</table>

25-11-16/users/app/views/contacts/new.html.erb
<h2 align= center ><strong>Create Contact</strong></h2>
<%= simple_form_for @contact do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :contact_type %>
  <%= f.input :address1 %>
  <%= f.input :address2 %>
  <%= f.input :city %>
  <%= f.input :phone_number %>
  <%= f.input :state %>
  
  <%= f.input :birthday %>
  <%= f.button :submit %>
 <% end %>

25-11-16/users/app/views/contacts/nocontact.html.erb
<%= link_to 'AddContact', new_contact_path %>

25-11-16/users/app/views/contacts/show.html.erb
<h1 align=center><strong>contact</strong></h2>
<p>
<strong>First_Name:</strong>
<%= @contact.first_name %>
</p>
<p>
<strong>Last_name:</strong>
<%= @contact.last_name%>
</p>
<p>
<strong>Contact-Type:</strong>
<%= @contact.contact_type %>
</p>

<p>
<strong>Address1:</strong>
<%= @contact.address1 %>
</p>

<p>
<strong>Phone No:</strong>
<%= @contact.phone_number %>
</p>
<p>
<strong>City:</strong>
<%= @contact.city %>
</p>
<p>
<strong>State:</strong>
<%= @contact.state %>
</p>
<p>
<strong>Birthday:</strong>
<%= @contact.birthday %>
</p>
<%= link_to 'Back', contacts_path %>

25-11-16/users/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
      <% if user_signed_in? %>
        <p align = right>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
       <% else %>
       <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
       <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
    <%= yield %>

  </body>
</html>

25-11-16/users/app/views/users/show.html.erb
<h1 align=center><strong>Profile</strong></h2>
<p>
<strong>First_Name:</strong>
<%= @profile.first_name %>
</p>
<p>
<strong>Gender:</strong>
<%= @profile.gender %>
</p>
<p>
<strong>Phone:</strong>
<%= @profile.phone %>
</p>
<strong>Email_Id:</strong>
<%= @profile.email %>
</p>
<p>
<strong>Address:</strong>
<%= @profile.address %>
</p>
<p>
<p>
<strong>HomeTown:</strong>
<%= @profile.hometown %>
</p>
<p>
<strong>Education:</strong>
<%= @profile.education %>
</p>
<p>
<strong>Story:</strong>
<%= @profile.story %>
</p>
<p>
<strong>Movies:</strong>
<%= @profile.movies %>
</p>
<p>
<%= button_to :AddContact, { :controller => :contacts, :action => "new",  }, :method => :get %>
<%= button_to :ListOfContacts, { :controller => :contacts, :action => "index",  }, :method => :get %>